import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
const ubuntu = Ubuntu({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Blog with comments",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log(
    process.env.REDIS_URL,
    process.env.NEXT_PUBLIC_AUTH0_CLIENT_ID,
    process.env.NEXT_PUBLIC_AUTH0_DOMAIN,
  );
  return (
    <html lang="en">
      <body
        className={`${ubuntu.className} bg-white text-gray-700 antialiased`}
      >
        <div className="container m-auto max-w-2xl px-4">
          <Header />
          <main className="py-14">{children}</main>
        </div>
      </body>
    </html>
  );
}
